version: 2
updates:
  # Backend PHP/Composer dependencies
  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "lomendor"
    assignees:
      - "lomendor"
    labels:
      - "dependencies"
      - "backend"
  
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/backend/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "lomendor"
    assignees:
      - "lomendor"
    labels:
      - "dependencies"
      - "frontend"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
    reviewers:
      - "lomendor"
    assignees:
      - "lomendor"
    labels:
      - "dependencies"
      - "ci"