name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'backend/docs/**'
      - '**/*.md'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - 'docs/**'
      - 'backend/docs/**'
      - '**/*.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependabot-smoke:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install frontend deps
        working-directory: frontend
        run: npm ci
      - name: Type check (dependabot)
        working-directory: frontend
        run: npm run type-check
      - name: PHP version check
        run: php -v

  backend:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_dixis_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql, mbstring, xml, ctype, json, tokenizer
          
      - name: Copy environment file
        run: cd backend && cp .env.example .env
        
      - name: Install dependencies
        run: cd backend && composer install --no-progress --prefer-dist --optimize-autoloader
        
      - name: Generate key
        run: cd backend && php artisan key:generate
        
      - name: Configure database
        run: |
          cd backend
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=project_dixis_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
        
      - name: Run migrations and seed
        run: cd backend && php artisan migrate:fresh --seed
        
      - name: Start backend server
        run: cd backend && php artisan serve --host=127.0.0.1 --port=8001 &
        
      - name: Wait for backend
        run: npx wait-on http://127.0.0.1:8001/api/health --timeout 60000
        
      - name: Run backend tests
        run: cd backend && php artisan test

  frontend:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    needs: backend
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Install contracts dependencies
        run: |
          if [ -d "packages/contracts" ]; then
            cd packages/contracts && npm ci
          else
            echo "No contracts directory found"
          fi

      - name: Build contracts package
        run: |
          if [ -d "packages/contracts" ]; then
            cd packages/contracts && npm run build
          else
            echo "No contracts directory found"
          fi

      - name: Type check
        run: cd frontend && npm run type-check
        
      - name: Build
        run: cd frontend && npm run build
        
      - name: Start frontend server
        run: cd frontend && npm run start &
        
      - name: Wait for frontend
        run: npx wait-on http://127.0.0.1:3001 --timeout 60000

  e2e:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    needs: [backend, frontend]
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_dixis_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql, mbstring, xml, ctype, json, tokenizer
          
      - name: Setup Node.js  
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install backend dependencies
        run: cd backend && composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Install frontend dependencies
        run: cd frontend && npm ci

      - name: Install contracts dependencies
        run: cd packages/contracts && npm ci

      - name: Install Playwright browsers
        run: cd frontend && npx playwright install --with-deps chromium
        
      - name: Setup backend environment
        run: |
          cd backend
          cp .env.example .env
          php artisan key:generate
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=project_dixis_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
        
      - name: Setup database
        run: cd backend && php artisan migrate:fresh --seed
        
      - name: Start backend server
        run: cd backend && php artisan serve --host=127.0.0.1 --port=8001 &
        
      - name: Build frontend
        run: cd frontend && npm run build
        
      - name: Start frontend server
        run: cd frontend && npm run start &
        
      - name: Wait for services
        run: |
          npx wait-on http://127.0.0.1:8001/api/health --timeout 60000
          npx wait-on http://127.0.0.1:3001 --timeout 60000
        
      - name: Run E2E tests
        run: cd frontend && npm run e2e
        env:
          CI: true
        
      - name: Upload Playwright artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: |
            frontend/playwright-report/
            frontend/test-results/
          retention-days: 7