name: Frontend E2E Tests

on:
  push:
    paths:
      - 'frontend/**'
      - 'backend/app/**'
      - 'backend/database/**'
      - 'backend/routes/**'
      - '.github/workflows/frontend-e2e.yml'
    paths-ignore:
      - 'docs/**'
      - 'backend/docs/**'
      - '**/*.md'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/app/**'
      - 'backend/database/**'
      - 'backend/routes/**'
    paths-ignore:
      - 'docs/**'
      - 'backend/docs/**'
      - '**/*.md'
  schedule:
    - cron: '0 3 * * *'  # Daily at 3:00 UTC
  workflow_dispatch:

concurrency:
  group: frontend-e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependabot-smoke:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]' }}
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Type check only (dependabot)
        run: npm run type-check || echo "no type-check script"

  e2e-tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]' }}
    
    defaults:
      run:
        working-directory: frontend
    
    env:
      FRONTEND_PORT: 3030
      PLAYWRIGHT_BASE_URL: "http://127.0.0.1:3030"
      NEXT_PUBLIC_API_BASE_URL: "http://127.0.0.1:8001/api/v1"
      PLAYWRIGHT_JOBS: 1
      PW_TEST_RETRIES: 2
      PW_TEST_TIMEOUT: 30000
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: project_dixis_test
        ports: ['5432:5432']
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      
      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-playwright-
      
      # Backend setup
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, intl, bcmath, pgsql, pdo_pgsql
          coverage: none
      
      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: backend/vendor
          key: composer-${{ runner.os }}-${{ hashFiles('backend/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-
            composer-
      
      - name: Install backend dependencies
        working-directory: backend
        run: composer install --no-interaction --prefer-dist
      
      - name: Copy .env
        working-directory: backend
        run: cp .env.example .env
      
      - name: Generate application key
        working-directory: backend
        run: php artisan key:generate
      
      - name: Configure DB env (testing)
        working-directory: backend
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=127.0.0.1" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=project_dixis_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "ALLOW_TEST_LOGIN=true" >> .env
      
      - name: Run migrations and seed
        working-directory: backend
        run: php artisan migrate:fresh --seed --env=testing
      
      - name: Start Laravel server
        working-directory: backend
        run: php artisan serve --host=127.0.0.1 --port=8001 --env=testing &
      
      - name: Wait for Laravel API
        run: |
          timeout 60 bash -c 'until curl -f http://127.0.0.1:8001/api/health; do sleep 2; done'
      
      # Frontend setup
      - name: Install frontend dependencies
        run: npm ci

      - name: Install and build contracts dependencies
        run: |
          if [ -d "../packages/contracts" ]; then
            cd ../packages/contracts
            npm ci
            npm run build
            cd ../../frontend
          else
            echo "No contracts directory found"
          fi

      - name: Set API base URL
        run: echo "NEXT_PUBLIC_API_BASE_URL=http://127.0.0.1:8001/api/v1" > .env.local
      
      - name: Install Playwright browsers with dependencies
        run: npx playwright install --with-deps
      
      - name: Build frontend
        run: npm run build || echo "no build step"
      
      - name: Start frontend server
        run: nohup npm run start -- -p ${{ env.FRONTEND_PORT }} > ../frontend.log 2>&1 &

      - name: Wait for frontend server
        run: |
          timeout 60 bash -c 'until curl -f http://127.0.0.1:${{ env.FRONTEND_PORT }}; do sleep 2; done'
      
      # Set E2E quarantine (branch-scoped)
      - name: Set E2E quarantine (branch-scoped)
        if: startsWith(github.head_ref, 'ci/')
        run: |
          echo "QUARANTINE_REGEX=Shipping Engine v1 - Error Handling & Edge Cases|Shipping Engine v1 - Producer Profile Integration|Shipping Engine v1 - Volumetric Weight Calculations|Shipping Engine v1 - Zone-based Calculations|Shipping Integration Demo|Shipping Integration E2E|Shipping Integration Final Demo|Shipping Integration Flow" >> $GITHUB_ENV

      # Run E2E tests
      - name: Run E2E
        run: npm run test:e2e:ci
      
      # Artifacts ΜΟΝΟ σε αποτυχία
      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: frontend/playwright-report
          retention-days: 3

      - name: Upload test artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pw-artifacts
          path: |
            frontend/test-results
            frontend/playwright/.cache
          retention-days: 3

      # Always upload artifacts for analysis
      - name: Upload Playwright report (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-playwright-report-always
          path: frontend/playwright-report/
          retention-days: 7

      - name: Upload test results (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results-always
          path: frontend/test-results/
          retention-days: 7