name: frontend-ci

on:
  push:
    paths:
      - 'backend/frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'backend/frontend/**'
  workflow_dispatch:

concurrency:
  group: frontend-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/frontend
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Run TypeScript type check
        run: npm run type-check
      
      - name: Build application
        run: npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: backend/frontend/.next/
          retention-days: 7

  e2e-tests:
    runs-on: ubuntu-latest
    needs: frontend-tests
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: dixis_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    defaults:
      run:
        working-directory: backend
    
    steps:
      - uses: actions/checkout@v4
      
      # Setup backend
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo, pdo_pgsql, mbstring, xml, ctype, json, tokenizer, openssl, curl, fileinfo
      
      - name: Install backend dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader
      
      - name: Copy environment file
        run: cp .env.example .env
      
      - name: Generate application key
        run: php artisan key:generate
      
      - name: Configure database
        run: |
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=dixis_test" >> .env
          echo "DB_USERNAME=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
      
      - name: Run migrations and seed
        run: |
          php artisan migrate --force
          php artisan db:seed --force
      
      - name: Start Laravel server
        run: php artisan serve --host=0.0.0.0 --port=8000 &
        
      # Setup frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/frontend/package-lock.json
      
      - name: Install frontend dependencies
        working-directory: backend/frontend
        run: npm ci
      
      - name: Install Playwright Browsers
        working-directory: backend/frontend
        run: npx playwright install --with-deps chromium
      
      - name: Start Next.js server
        working-directory: backend/frontend
        run: npm run build && npm start &
      
      - name: Wait for servers to be ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:8000/api/health; do sleep 2; done'
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
      
      - name: Run E2E tests
        working-directory: backend/frontend
        run: npm run e2e
        env:
          CI: true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: backend/frontend/playwright-report/
          retention-days: 7